import { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { 
  Bell, ShieldAlert, AlertTriangle, Info, 
  CheckCircle2, Clock, Trash2, ShieldCheck,
  Filter, Search, ExternalLink
} from 'lucide-react';
import { alertService } from '../services/api';
import { Alert } from '../types';
import { cn } from '../lib/utils';
import { format } from 'date-fns';

export default function Alerts() {
  const [alerts, setAlerts] = useState<Alert[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    async function fetchData() {
      try {
        const a = await alertService.getAlerts();
        setAlerts(a);
      } catch (err) {
        console.error(err);
      } finally {
        setLoading(false);
      }
    }
    fetchData();
  }, []);

  const getSeverityColor = (sev: string) => {
    switch (sev) {
      case 'CRITICAL': return 'text-cyber-red border-cyber-red bg-cyber-red/5';
      case 'HIGH': return 'text-orange-500 border-orange-500 bg-orange-500/5';
      case 'MEDIUM': return 'text-cyber-yellow border-cyber-yellow bg-cyber-yellow/5';
      default: return 'text-cyber-blue border-cyber-blue bg-cyber-blue/5';
    }
  };

  const getIcon = (sev: string) => {
    switch (sev) {
      case 'CRITICAL': return <ShieldAlert size={20} />;
      case 'HIGH': return <AlertTriangle size={20} />;
      case 'MEDIUM': return <Info size={20} />;
      default: return <Bell size={20} />;
    }
  };

  if (loading) return <div className="text-cyber-blue font-mono animate-pulse">LISTENING TO GLOBAL THREAT FEED...</div>;

  return (
    <div className="space-y-8 max-w-5xl mx-auto">
      <div className="flex justify-between items-end">
        <div>
          <h2 className="text-2xl font-bold text-white flex items-center gap-3">
            Threat Intelligence Feed
            <div className="px-2 py-0.5 bg-cyber-red text-white text-[10px] rounded animate-pulse">LIVE</div>
          </h2>
          <p className="text-gray-400 text-sm">Real-time alerts generated by the CSG Cyber Alert Engine.</p>
        </div>
        <div className="flex gap-2">
           <button className="cyber-button-primary bg-white/5 border-cyber-border text-gray-400 hover:text-white">
             Mark All Resolved
           </button>
        </div>
      </div>

      <div className="flex gap-4">
        <div className="flex-1 relative">
           <Search size={18} className="absolute left-3 top-2.5 text-gray-500" />
           <input type="text" placeholder="Filter alerts by type or hostname..." className="cyber-input w-full pl-10" />
        </div>
        <button className="cyber-panel p-2 flex items-center justify-center hover:bg-white/5">
          <Filter size={18} className="text-cyber-blue" />
        </button>
      </div>

      <div className="space-y-4">
        <AnimatePresence>
          {alerts.map((alert, i) => (
            <motion.div
              layout
              initial={{ opacity: 0, x: -10 }}
              animate={{ opacity: 1, x: 0 }}
              exit={{ opacity: 0, x: 10 }}
              transition={{ delay: i * 0.05 }}
              key={alert.id}
              className="cyber-panel p-0 flex items-center group relative overflow-hidden"
            >
              <div className={cn("stat-card-indicator", alert.severity === 'CRITICAL' && "stat-card-indicator-alert")} />
              
              <div className={cn(
                "w-12 h-12 flex items-center justify-center shrink-0 border-r border-cyber-border bg-white/5",
                alert.severity === 'CRITICAL' ? "text-cyber-red" : "text-cyber-blue"
              )}>
                {getIcon(alert.severity)}
              </div>

              <div className="flex-1 px-6 py-4">
                <div className="flex items-center gap-3">
                  <h4 className="font-bold text-white uppercase tracking-tight text-sm">{alert.type}</h4>
                  <span className={cn("status-tag shadow-sm", getSeverityColor(alert.severity))}>
                    {alert.severity}
                  </span>
                  <p className="text-[10px] text-cyber-text-muted font-mono flex items-center gap-1 ml-auto">
                    {format(new Date(alert.timestamp), 'HH:mm:ss')}
                  </p>
                </div>
                <p className="text-[12px] text-cyber-text-muted mt-1">{alert.message}</p>
                <div className="flex items-center gap-4 mt-2">
                  <p className="text-[9px] text-cyber-blue font-bold uppercase tracking-widest bg-cyber-blue/5 px-2 py-0.5 rounded-sm">TARGET: {alert.hostname}</p>
                </div>
              </div>

              <div className="pr-6 flex gap-2 opacity-0 group-hover:opacity-100 transition-opacity">
                <button className="px-3 py-1 bg-cyber-blue/10 text-cyber-blue text-[9px] font-bold border border-cyber-blue/20 hover:bg-cyber-blue hover:text-black transition-all uppercase tracking-widest">
                  Investigate
                </button>
              </div>
            </motion.div>
          ))}
        </AnimatePresence>
      </div>

      <div className="mt-12 p-8 border border-dashed border-cyber-border rounded-xl text-center space-y-4">
        <ShieldCheck size={48} className="mx-auto text-gray-700" />
        <div>
           <p className="text-gray-500 font-mono text-sm uppercase">End of Signal Feed</p>
           <p className="text-xs text-gray-600 mt-2">Historical logs beyond 24H are moved to ARCHIVE_VAULT.</p>
        </div>
      </div>
    </div>
  );
}
